name: Your New Jekyll Site
encoding: utf-8
markdown: redcarpet
pygments: false
exclude:
  - CNAME
  - README.md
  - run.bat
  - orig
redcarpet:
  extensions:
    - tables
    - autolink
gems:
  - jekyll-redirect-from
